apiVersion: v1
kind: Service
metadata:
  name: chatbox-fe-service
  labels:
    app: chatbox-fe-service
spec:
  selector:
    app: chatbox-fe
  type: NodePort
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30000