apiVersion: v1
kind: Service
metadata:
  name: model-qaa-service
  labels:
    app: model-qaa-service
spec:
  selector:
    app: model-qaa
  type: NodePort
  ports:
    - protocol: TCP
      port: 8386   
      targetPort: 8386 
      nodePort: 30000