apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:9.0.1
        env:
        - name: ELASTICSEARCH_HOSTS
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: ELASTICSEARCH_HOSTS
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
           secretKeyRef:
             name: kibana-secret
             key: ELASTICSEARCH_USERNAME
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
           secretKeyRef:
             name: kibana-secret
             key: ELASTICSEARCH_PASSWORD
        ports:
        - containerPort: 5601


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kibana
# spec:
#   selector:
#     matchLabels:
#       component: kibana
#   template:
#     metadata:
#       labels:
#         component: kibana
#     spec:
#       containers:
#       - name: kibana
#         image: docker.elastic.co/kibana/kibana:7.12.0
#         env:
#         - name: ELASTICSEARCH_URL
#           value: http://elasticsearch:9200
#         - name: XPACK_SECURITY_ENABLED
#           value: "true"
#         - name: ELASTICSEARCH_USERNAME
#           valueFrom:
#             secretKeyRef:
#               name: kibana-secret
#               key: ELASTICSEARCH_USERNAME
#         - name: ELASTICSEARCH_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: kibana-secret
#               key: ELASTICSEARCH_PASSWORD
#         ports:
#         - containerPort: 5601
#           name: http
#           protocol: TCP