apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enrollment.enabled
          value: "true"

        - name: xpack.security.enabled
          value: "true"

        - name: xpack.graph.enabled
          value: "false"
        - name: xpack.watcher.enabled
          value: "false"
        - name: xpack.ml.enabled
          value: "false"
        ports:
        
        - containerPort: 9200
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es-data
        emptyDir: {}